# Generated by Django 5.2 on 2026-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='dt_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
